# Use the basic Python 3 image as launching point
FROM ubuntu

# Update

# Add the script to the Dockerfile


RUN ["apt-get", "update"]
RUN ["apt-get", "install", "python","-y"]
RUN ["apt-get", "install","python-pip","-y"]
RUN ["apt-get", "install","python3-pip","-y"]
RUN ["apt-get", "install","python3-tk","-y"]
ADD ADSassignment.py /home
RUN ["pip3", "install", "bs4"]
RUN ["pip3", "install", "lxml"]
CMD ["pip3", "install", "bs4"]
CMD ["pip3", "install", "lxml"]
CMD ["pip3", "install", "urllib3"]
RUN ["pip3", "install", "boto"]
CMD ["pip3", "install", "numpy"]
RUN ["pip3", "install", "numpy"]
RUN ["pip3", "install", "requests"]
CMD ["pip3", "install", "requests"]
RUN ["pip3", "install", "pandas"]
CMD ["pip3", "install", "pandas"]
RUN ["pip3", "install", "seaborn"]
CMD ["pip3", "install", "seaborn"]
# Execute the script